[workspace]
members = ["core", "gnome"]
resolver = "2"

[workspace.dependencies]
# For communication between core and ui
flume = "0.11.1"

# Everything else
regex = "1.11"
grep = "0.3"
ignore = "0.4"
dotext = { git = "https://github.com/anvie/dotext.git", rev = "06b1600" }
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }
toml = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
env_logger = { version = "0.11.8", default-features = false }
anyhow = "1.0.98"
glob = "0.3.2"

# Anything glib related
[workspace.dependencies.gtk]
version = "0.10.0"
package = "gtk4"
features = ["blueprint", "v4_16"]

[workspace.dependencies.adw]
version = "0.8.0"
package = "libadwaita"
features = ["v1_7"]

[workspace.dependencies.gio]
version = "0.21.0"
features = ["v2_84"]

[workspace.dependencies.sourceview5]
version = "0.10.0"
features = ["gtk_v4_12", "v5_12"]

[workspace.dependencies.poppler-rs]
version = "0.25.0"
features = ["v23_8"]
