use adw::prelude::*;
use gtk::{
    gio::{self, ApplicationFlags},
    glib,
};

mod app;
mod color;
mod config;
mod i18n;
mod search;
mod ui;

// generated by Meson
mod build;

fn main() {
    env_logger::init();

    i18n::setup_gettext();

    gtk::init().expect("Failed to initialize Gtk");
    adw::init().expect("Failed to initialize Adwaita");
    sourceview5::init();

    gio::resources_register(
        &gio::Resource::from_data(&glib::Bytes::from_static(build::GRESOURCES_BUNDLE)).unwrap(),
    );

    let application = adw::Application::builder()
        .application_id(build::APP_ID)
        .flags(ApplicationFlags::HANDLES_OPEN)
        .build();

    application.connect_open(|a, files, _| app::start(a, files));
    application.connect_activate(|a| app::start(a, &[]));

    application.run();
}
